/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package authentication;

import javax.swing.JOptionPane;
//personal added imports here
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;

//others
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;

//excel
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.VerticalAlignment;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author franz
 */
public class Patient_Registration extends javax.swing.JInternalFrame {

    //Connection Db - DATABASE CONNECTION
    Connection con = (Connection) connectionDB.getConnectionDB();

    /**
     * Creates new form Patient_Registration
     */
    public Patient_Registration() {
        initComponents();
        retrieve();
    }

    void openFile(String file) {
        try {
            File path = new File(file);
            Desktop.getDesktop().open(path);
        } catch (IOException E) {
            E.printStackTrace();
        }
    }

    public static String fname, lname;
    String patID, dateR, dateB, gender, weight, height, address, account;
    public static String patIDs = "";

    void retrieve() {
        String query = "SELECT*FROM patient_registration "
                + "Inner join address on patient_registration.F_Address = Add_code "
                + "Inner join account on patient_registration.F_Account= Acc_id ";

        DefaultTableModel dtm = (DefaultTableModel) patreg_data.getModel();
        dtm.setRowCount(0);

        try {
            PreparedStatement pst = (PreparedStatement) con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {

                patID = rs.getString("Patient_Id");
                lname = rs.getString("Patient_lname");
                fname = rs.getString("Patient_fname");
                dateR = rs.getString("Date_admission");
                dateB = rs.getString("Birthdate");
                gender = rs.getString("Gender");
                weight = rs.getString("Weight");
                height = rs.getString("Height");
                address = rs.getString("Barangay") + ", " + rs.getString("Municipality") + ", " + rs.getString("Province");
                account = rs.getString("Acc_Name");

                dtm.addRow(new Object[]{patID, lname, fname, dateR, dateB, gender, weight, height, address, account});
            }

        } catch (SQLException ex) {
            Logger.getLogger(Patient_Registration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        patreg_data = new javax.swing.JTable();
        add_patient = new javax.swing.JButton();
        add_medrec = new javax.swing.JButton();
        exportexcel = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 0, 0));
        setFrameIcon(null);
        setMaximumSize(new java.awt.Dimension(786, 413));
        setMinimumSize(new java.awt.Dimension(786, 413));
        setPreferredSize(new java.awt.Dimension(974, 581));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(774, 581));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("List of Registered Patients");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        patreg_data.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        patreg_data.setForeground(new java.awt.Color(0, 102, 102));
        patreg_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID No.", "Last Name", "First Name", "Date Registered", "Date of Birth", "Gender", "Weight", "Height", "Address", "Account"
            }
        ));
        patreg_data.setToolTipText("");
        patreg_data.setSelectionBackground(new java.awt.Color(0, 102, 153));
        patreg_data.setSelectionForeground(new java.awt.Color(255, 255, 255));
        patreg_data.getTableHeader().setReorderingAllowed(false);
        patreg_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                patreg_dataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(patreg_data);

        add_patient.setText("Add Patient");
        add_patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_patientActionPerformed(evt);
            }
        });

        add_medrec.setText("Add Medical Record");
        add_medrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_medrecActionPerformed(evt);
            }
        });

        exportexcel.setText("Export Excel");
        exportexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportexcelActionPerformed(evt);
            }
        });

        jButton2.setText("Manage Patient");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 938, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(add_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(add_medrec, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exportexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_medrec, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_patient, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 36, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 950, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void add_patientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_patientActionPerformed
        // TODO add your handling code here:
        AddPatreg apr = new AddPatreg();
        apr.setVisible(true);
    }//GEN-LAST:event_add_patientActionPerformed

    private void add_medrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_medrecActionPerformed
        // TODO add your handling code here:

        AddMedrec amr = new AddMedrec();
        amr.setVisible(true);
    }//GEN-LAST:event_add_medrecActionPerformed

    private void exportexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportexcelActionPerformed
        // TODO add your handling code here:
        try {
            Workbook wb = new XSSFWorkbook();
            Sheet sheet = wb.createSheet("Sample");
            Row row;
            Cell cell;

            CellStyle style1 = wb.createCellStyle();

            style1.setAlignment(HorizontalAlignment.CENTER);
            style1.setVerticalAlignment(VerticalAlignment.CENTER);

            //HEADER
            row = sheet.createRow(1);
            sheet.addMergedRegion(new CellRangeAddress(1, 1, 0, 10));
            cell = row.createCell(0);
            cell.setCellValue("LIST OF REGISTERED PATIENTS");
            cell.setCellStyle(style1);

            //number of column
            row = sheet.createRow(2);
            for (int i = 0; i < 10; i++) {
                cell = row.createCell(i);
                cell.setCellValue(patreg_data.getColumnName(i));
                cell.setCellStyle(style1);
            }

            //rows
            row = sheet.createRow(3);
            for (int i = 0; i < patreg_data.getRowCount(); i++) {
                row = sheet.createRow(i + 3);

                for (int j = 0; j < 10; j++) {
                    cell = row.createCell(j);
                    cell.setCellValue((String) patreg_data.getValueAt(i, j));

                    cell.setCellStyle(style1);
                }
            }

            //OUTPUT
            FileOutputStream out = new FileOutputStream(new File("C:\\Users\\franz\\Downloads\\Registered_Patients\\patreg.xlsx"));

            wb.write(out);
            wb.close();
            out.close();
            JOptionPane.showMessageDialog(null, "Exported successfully!");
            openFile("C:\\Users\\franz\\Downloads\\Registered_Patients\\patreg.xlsx");
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_exportexcelActionPerformed

    private void patreg_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patreg_dataMouseClicked
        // TODO add your handling code here:
        patIDs = (String) patreg_data.getValueAt(patreg_data.getSelectedRow(), 0);
    }//GEN-LAST:event_patreg_dataMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ManagePatient mp = new ManagePatient();
        mp.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_medrec;
    private javax.swing.JButton add_patient;
    private javax.swing.JButton exportexcel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable patreg_data;
    // End of variables declaration//GEN-END:variables
}
